### ISSUE TITLE
ResourcePath.copy & TM metadata files

### ISSUE THREAD

**Issue by buildersbrewery** [SublimeText/sublime_lib#110]
When writing to TextMate metadata files, `newline='\n'` is needed as in:

```py
with open(METADATA_TARGET, mode='w', newline='\n') as file:
    file.write(NEW_CONTENT)
```

otherwise Sublime Text won't work as expected.

**Comment by Thom1729** [comment]
`ResourcePath.copy` is implemented as follows:

```python
    def copy(self, target, exist_ok=True):
        if exist_ok:
            mode = 'w'
        else:
            mode = 'x'

        data = self.read_bytes()
        with open(str(target), mode + 'b') as file:
            file.write(data)
```

The resource is read and written in binary mode. The `newline` argument only applies in text mode.

Can you provide a bit more detail about what the problem is?

**Comment by buildersbrewery** [comment]
@Thom1729 I hadn't tested `copy` yet, due to the missing newline option argument...and somehow missed the binary flag while reading the docs and your code. I will test and report back.

**Comment by Thom1729** [comment]
We can reopen this if testing reveals a problem.

**Comment by buildersbrewery** [comment]
@Thom1729 thanks for clarifying, works as expected with the `b` flag
