### ISSUE TITLE
Documentation pages broken

### ISSUE THREAD

**Issue by rchl** [SublimeText/sublime_lib#118]
https://sublimetext.github.io/sublime_lib/ page seems broken as I can't click any of the headers or links to reveal more info about specific API.

**Comment by Thom1729** [comment]
Yeah, there should be docs there. Thanks for the heads-up.

**Comment by FichteFoll** [comment]
Looks like #120 didn't do it. Doc pages are still broken.

**Comment by Thom1729** [comment]
I got the docs working for now by building them manually and pushing the, to the `gh-pages` branch.

**Comment by FichteFoll** [comment]
So it only fails on CI? Seems annoying.

**Comment by Thom1729** [comment]
Yeah, I've been running it successfully on Mac OS, Fedora, and even Windows. No idea why the CI is different.

**Comment by FichteFoll** [comment]
I don't quite remember how the docs looked before #120, but considering that didn't help, do we want to revert that?

**Comment by Thom1729** [comment]
#120 removed the type annotations added by #116, which were a mess. Sphinx basically just dumps the function signature as a string with no formatting or `<span>`s or anything, so signatures with complex types look awful. I suspect that solving this will require a custom extension.

**Comment by FichteFoll** [comment]
Still broken (or broken again).

I might use this opportunity to experiment with Github Actions when I look into it, but no promises.

**Comment by FichteFoll** [comment]
Fixed via 5f8474f8a4eb87f0d9e9ac22341453c37512051a. I'm disabling Travis.
