### ISSUE TITLE
1.4.0 release

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#122]
It's probably a good time for a minor release once the ActivityIndicator stuff is done.

# Version 1.4.0

## Enhancements

- Add `ActivityIndicator`. (#119)
- Add `HoverLocation`, `QueryContextOperator`, and `CompletionOptions` enums. (#111)

## Bug Fixes

- Fix bug in glob matching. (#117)
- Add missing default value of `-1` for the `size` argument of `ViewStream.read()`.

## Internal changes

- Add comprehensive type declarations. (#116 )
- If a `pathlib` is available, use that instead of the vendored version. (#113)
- Improved performance of `ResourcePath.from_file_path()`. (#112)

**Comment by Thom1729** [comment]
@FichteFoll are we good to release 1.4.0?

**Comment by FichteFoll** [comment]
Well, we still haven't been able to figure out why CI is failing to build the docs properly, but the manual process should work for now. Maybe we want to refer to https://github.com/SublimeText/sublime_lib/releases for a changelog.

**Comment by Thom1729** [comment]
[v1.4.0 is out.](https://github.com/SublimeText/sublime_lib/releases/tag/v1.4.0)
