### ISSUE TITLE
Add more entries to prettify_special_methods.SPECIAL_METHODS

### ISSUE THREAD

**Issue by eric-wieser** [SublimeText/sublime_lib#135]
There are a few you missed that could be added:

* `__call__(...)` &rarr; `self(...)`
* `__getattr__(attr)` &rarr; `getattr(self, attr)`
* `__setattr__(attr, value)` &rarr; `setattr(self, attr, value)`
* `__detattr__(attr)` &rarr; `detattr(self, attr)`
* `__index__()` &rarr; `operator.index(self)`
* `__length_hint__()` &rarr; `operator.length_hint(self)`
* `__ceil__()` &rarr; `math.ceil(self)`
* `__floor__()` &rarr; `math.floor(self)`
* `__trunc__()` &rarr; `math.trunc(self)`

**Comment by FichteFoll** [comment]
Since it seems we're [vendoring that extension](https://github.com/SublimeText/sublime_lib/blob/e8aeb59eacb14c52836c4210c0b011aaaf81da96/docs/source/extensions/prettify_special_methods.py), I'll reopen the issue until someone looked into updating that and rebuilding the docs.

@Thom1729 ?

**Comment by eric-wieser** [comment]
It's not that you're vendoring to, but that I've extracted your implementation (with history + license) to a standalone package so that I can use it in my own docs.

It would probably make sense to unvendor before doing a release, but I'd like to make contact with #Thom1729 first.

**Comment by FichteFoll** [comment]
Ah, that makes sense. I just noticed it being under the "sphinx-contrib" org. I see now that you git-subtree'd the extension.

**Comment by Thom1729** [comment]
Unvendoring after the extension is released sounds sensible.

**Comment by eric-wieser** [comment]
I've released this as https://pypi.org/project/sphinxcontrib-prettyspecialmethods/.
