### ISSUE TITLE
Request for a threadless activity indicator

### ISSUE THREAD

**Issue by rwols** [SublimeText/sublime_lib#140]
The current ActivityIndicator spawns a thread. There is some noticeable overhead associated with this thread. I'm noticing some stuttering when the indicator starts. Would it be possible to have a design that utilizes the assumption that the main thread is never blocked?

**Comment by rchl** [comment]
I did make a main-thread variant in https://github.com/sublimelsp/lsp_utils/pull/47 just to see if it performs well and I don't see it causing any blocking issues or even registering on the `Profile plugins` table.
