### ISSUE TITLE
1.4.1 release (or 1.5.0?)

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#158]
The remainder of the open PRs should probably make it as well.

Since we do have some enhancements, it might be appropriate to do a minor release. Once this release is out, I'd like to start on a couple larger features, including #141 and #136.

# Enhancements

- ActivityIndicator no longer uses a thread. (#140)
- Two SettingsDicts are equal if and only if they are the same type and refer to the same underling Settings object. (#129)
- Add the Central European (Mac) encoding. (#138)

# Bug Fixes

- When an ActivityIndicator is garbage collected, it should stop running. (#153)
- When modifying settings in a `SettingsDict.subscribe()` callback, don't call the subscription again if the subscribed settings haven't changed. (#152)
- When force-closing views with `close_view()` or `close_window()`, revert the scratch state of any clones of those views. (#147)
- A glob pattern like `foo/**/*` shouldn't match `foo/`. (#134)

# Documentation Changes

- Improved `SettingsDict.subcribe` documentation to clarify how it detects changes in the selected value.

**Comment by Thom1729** [comment]
@FichteFoll I think I'm going to release later today/tomorrow as 1.5.0. Any objections?

**Comment by FichteFoll** [comment]
None from my side. Unless you made changes without a PR that I haven't reviewed. 😉
