### ISSUE TITLE
Syntax utilities

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#16]
Basically, implement https://github.com/SublimeTextIssues/Core/issues/2186. We'd probably want a method that provides a list of all loaded syntax definitions and their associated metadata (at least name and scope) and a method to map a scope to a syntax definition. 

The potential obstacle is performance: doing this the obvious way would be unacceptably slow. I have some yet-untested ideas for doing it more efficiently.

**Comment by FichteFoll** [comment]
When this is implemented, I strongly suggest a manual text/regex-based approach for determining the syntax's name (and scope) rather than using a full-featured yaml parser. When that custom parser can't handle a complex situation, just set the metadata property to `None`.

For plists this might turn out harder.

**Comment by FichteFoll** [comment]
Yeah, `plistlib` is a thing, but I'm not sure about its performance. Fortunately all the default syntaxes use the new format though, so we most likely don't have to  parse that many tmLanguage files. I've had problems with it in ST2 on Linux through PackageDev, but that's long gone.

Why do we need `ExtendedPlistParser`, though?

**Comment by FichteFoll** [comment]
>The built-in one only reads from named files and binary streams, not from strings.

There is `plistlib.readPlistFromBytes` (and from 3.4 onwards `plistlib.loads`).

>The get_syntax_for_scope really should explicitly implement Sublime's priority algorithm, which I can't quite recall. Is it officially documented?

No, I don't think so.

**Comment by Thom1729** [comment]
`loads` and `readPlistFromBytes` only work with bytes, so we'd have to `encode` the string. On the other hand, the underlying XML parser will handle strings natively. I imagine that it should be faster to save the extra re-encoding step. I suppose I should measure.

**Comment by FichteFoll** [comment]
We don't have to encode the string if we use sublime.load_binary_resource.

**Comment by Thom1729** [comment]
…well, that's definitely an API function that's existed this whole time.

I'll take a look tomorrow. The Sublime update seems to be interfering with the slightly insane way that UnitTesting handles its imports.

**Comment by Thom1729** [comment]
See #22.

**Comment by FichteFoll** [comment]
Done via #17 and #22.
