### ISSUE TITLE
Type annotations don't work correctly with pyright

### ISSUE THREAD

**Issue by rchl** [SublimeText/sublime_lib#171]
Opening this project in ST with LSP-pyright enabled highlights all type annotations with errors. This is because pyright can't handle try/except based import logic like in:
https://github.com/SublimeText/sublime_lib/blob/54bcf41ee8de4a7c6482a3e60aa0d72383465d96/st3/sublime_lib/_compat/typing.py
It will always use the "last" import in such case.

The solution to that is doing a check based on python version like in: https://github.com/sublimelsp/LSP/blob/7fc1f80c3d3730b34d1f2fb8be65e41cfb43f2fe/plugin/core/typing.py#L3-L3

Fixing that would improve developer experience.

**Comment by Thom1729** [comment]
I'd like to get it working with pyright, but I've had other issues as well. For instance, it seems to complain about using `Union[T, U]` instead of the new `T | U` syntax. I may need to change my configuration.

**Comment by rchl** [comment]
It does show error but with clear explanation why it's shown:

![Screenshot 2021-05-18 at 18 05 55](https://user-images.githubusercontent.com/153197/118685987-e0270b80-b803-11eb-9fd0-e79a3c9423c6.png)

The python version should be controllable with the `pythonVersion` setting in the [configuration file](https://github.com/microsoft/pyright/blob/main/docs/configuration.md)

**Comment by rchl** [comment]
But for compatibility with the ST runtime I guess you wouldn't want to use that new syntax.

**Comment by rwols** [comment]
Noticed this as well :)

<img width="903" alt="image" src="https://user-images.githubusercontent.com/2431823/119257975-0fed5f00-bbc8-11eb-8106-c3de03482259.png">

**Comment by rchl** [comment]
This is likely related because it uses stubbed `List` type here instead of the proper one.
