### ISSUE TITLE
Feature request: A way to save without closing autocomplete popups

### ISSUE THREAD

**Issue by scholer** [SublimeText/sublime_lib#20]
Currently, invoking `view.run_command("save")` has the same effect as pressing Ctrl+s, and will close any open autocomplete menus. For plugins that invoke the save command periodically/automatically this may interfere with the user experience. You don't want your autocomplete menus to disappear while trying to select the right completion. (Case in point: the auto-save plugin.) While the plugins could use the API to determine if an autocomplete menu is visible (`is_auto_complete_visible`), this is not optimal, and could interfere with the plugin's expected use. In some cases, the autocomplete menu may be visible the majority of the time. Or the user could just leave the computer mid-word with the autocomplete menu open, preventing auto-save from ever saving the document.  

The optimal way to solve this would be to accept a parameter to the save command, e.g. `view.run_command("save", {'hide_menus': False})`. Providing no *args* defaults to the existing behaviour. But passing `hide_menus=False` would save the view *without* closing autocomplete menus. Basically just writing the view to its file with no side effects.

**Comment by FichteFoll** [comment]
You're at the wrong repo for feature requests against sublime text core. This repository is about utilities that are provided to other python packages (and most likely it won't define any commands because then it would be directly interfacing with sublime_plugin).

See https://github.com/SublimeTextIssues/Core for feature requests like yours.

**Comment by scholer** [comment]
Well, to be fair, it is kind of confusing that the "Core" repository is nowhere to be found under https://github.com/SublimeText, and people somehow have to know to go to https://github.com/SublimeTextIssues to find the right repository to submit feature requests. This repository, OTOH, is at the very top when people go to https://github.com/SublimeText, which is the organization/collection at the top when searching for "sublime text github" on google.

**Comment by FichteFoll** [comment]
There are a couple reasons for why the orgs are set up the way they are, but to make it short it's mostly a) historical and b) different people starting the Issues org (which also had a different name before).
