### ISSUE TITLE
Utilities for working with Sublime resource paths

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#25]
Many Sublime features and API functions deal with resource paths, such as `Packages/JavaScript.JavaScript.sublime-syntax`. On the other hand, OS features require "real" system paths. When working with Sublime resources, one often must keep track of both the Sublime resource path and the system path.

For example, when running JS Custom's syntax tests, I need to:

- Locate the test directory.
- Clear/create it (by system path).
- Compile a test syntax into the test directory (by system path).
- Copy a syntax test file into the test directory (by system path).
- Modify the syntax test (by system path) to refer to the compiled test syntax file (by resource path).
- Tell the Sublime API to run the syntax test (by resource path).

Keeping separate track of the resource and system paths to the several files involved is annoying, verbose, and error-prone.

Another example is the suggested resource caching system in #24. The cache takes requests for sublime resources, but to implement the caching it also needs the system file path and last modification time. Other packages that want to work with resources in more sophisticated ways, such as [OverrideAudit](https://github.com/OdatNurd/OverrideAudit/) and [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer/), have to solve these problems manually.

A convenient general-purpose system for dealing with resources could be very useful to package developers, helping them to solve some otherwise tricky problems while getting the corner cases right. As you may have guessed, I'm writing this here because I think that we can provide such a system.

The lightweight solution might be a handful of utility functions to convert between resource and system paths. We might also provide functions to (for example) get the last modification time of a resource.

A more comprehensive solution would be to define a SublimeResource type inspired by [pathlib](https://docs.python.org/3/library/pathlib.html). As with pathlib, users could perform all of the common file operations on a SublimeResource -- reading text or binary data, listing directory contents, and so on. These operations would abstract away the underlying complexity of the resource system. For instance, `read_bytes` and `read_text` would be implemented using `sublime.load_binary_resource` and `sublime.load_resource`, whereas `iterdir` would be implemented using both `os.listdir` and `ZipFile.namelist`. In addition, SublimeResource would provide Sublime-specific functionality, like extracting the package name. Ideally, we could provide a `Path`-compatible interface, though a few methods might not be supportable.

Thoughts?

**Comment by FichteFoll** [comment]
I can see the problem, but I'm not seeing the solution yet.

Doing something similar to pathlib seems nice for the mirrored interface (and that it would wrap `sublime-packages` files to its best ability, but you don't fully solve the problem with that since you still have to keep track of different path types for different purposes.
For this, it might be easiest to just have a function to translate between system and resource paths and then use them in code at appropriate exit points.

If a pathlib-like class was implemented, it would make sense to add a method to convert it to a system path and to have it automatically recognize the type of the input path in its constructor (`__new__`, as it should be immutable).

**Comment by Thom1729** [comment]
The idea is that a single `SublimeResource` would be able to handle all of the usual `Path` operations, so you wouldn't need to work with more than one kind of path for a given resource. Here's how the JS Custom example above might be implemented:

```python
test_dir = SublimeResource('Packages/User/JS Custom/tests')
test_dir.mkdir(parents=True, exist_ok=True)

syntax_path = test_dir / 'example.sublime-syntax'
yamlmacros.compile(some_stuff, to=syntax_path.system_path) # Actual call elided.

syntax_test_sources = SublimeResource('Packages/JSCustom/tests/syntax_test_example.js').glob('syntax_test_*.js')
for source in syntax_test_sources:
    dest_path = test_dir / source.name
    with dest_path.open('w') as dest:
        dest.write('// SYNTAX TEST "%s"\n' % syntax_path.resource_path)
        dest.write(source.read_text())

    sublime_api.run_syntax_test(dest_path.resource_path)
```

Sometimes, we do need the real OS path (interfacing with YAML Macros). Sometimes, we need the resource path (for parts of the syntax test). But 

Most of the operations can be performed directly with the `SublimeResource` object. For instance, the line `syntax_test_sources = SublimeResource('Packages/JSCustom/tests/syntax_test_example.js').glob('syntax_test_*.js')` works regardless of whether the package is installed as a directory under Packages or as a zipfile under Installed Packages. Sometimes, we do need the “escape hatch” of `resource_path` or `system_path`, and it's there for that purpose.

Without the `SublimeResource` object, I have to separately build a `syntax_system_path` and a `syntax_resource_path`, and likewise for the path to the syntax test. In addition, there's nothing like `glob` for finding the syntax test sources: I'd have to case it out depending on how the package was installed.

**Comment by FichteFoll** [comment]
I do kind of wonder about the performance of iterating on the zip files, but they are indexed and usually not large, so it will probably work out just fine.

Imo this is a worthwhile addition.

**Comment by Thom1729** [comment]
I've been digging into the zip format, and it looks like iterating over the contents should be reasonable-ish outside of pathological cases. The central directory record is at the *end*, and the only way to find it is to search backward through the file; this should be fast enough on the scale of file operations. It's unfortunate that sublime packages seem to have zip file comments; that will prevent the `zipfile` implementation from using the most optimized case. If those comments aren't used for anything (I expect they aren't), then stripping them during package installation could speed up most operations involving those files.

On an unrelated note, it would probably make sense to port `pathlib` while we're at it. It would simplify the implementation, and then we might as well expose it.

**Comment by FichteFoll** [comment]
Most sublime-package files are going to be created by Package Control (and the zipfile module), so this is at least something we could change. If we think it's necessary or worth it.

**Comment by Thom1729** [comment]
Never mind on the comments; I misread the `zipfile` source. It looks like the `sublime-package` files produced by Package Control do not contain comments, and they will hit the fastest code path in `zipfile` (finding the end record at the very end of the file rather than having to search).

Now, the obstacle is that Python 3.3 does not implement `scandir`, which might make the whole thing a lot trickier than I expected.

**Comment by FichteFoll** [comment]
Why would we need `scandir`? To determine whether something is a dict? Maybe we want `os.walk` instead? I mean, for discovering the contents of a folder, there is `listdir` and there is also https://github.com/packagecontrol/pathlib which we can use for recursive globbing. Or we just use `glob.glob`.
