### ISSUE TITLE
Wrapper for `Window.show_quick_panel` to choose an item from a list.

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#31]
The most common use for `Window.show_quick_panel` is to choose one item from a list of items, then do something with the result. The API for the method is a bit inconvenient. You pass in a list of labels, and the callbacks get a numerical index. Most of the time, that index is not particularly meaningful; you have to index your original list to find out what it's for (after checking that it isn't `-1`). This makes for a fair bit of boilerplate in this common case:

```python
syntaxes = [
    s for s in sublime_lib.syntaxes.list_syntaxes()
    if not s.hidden
]

labels = [ s.name for s in syntaxes ]

def on_selected(index):
    if index == -1:
        return

    syntax = syntaxes[index]
    do_something_with_syntax(syntax)

window.show_quick_panel(
    items=labels,
    on_done=on_selected
)
```

This example is (reconstructed from memory) from a syntax selection package I'm working on, but I've seen this pattern many places. Instead, I suggest a utility function providing a simpler interface inspired by typical HTML `<select>` widgets:

```python
show_selection_panel(
    window,
    items=[
        s for s in sublime_lib.syntaxes.list_syntaxes()
        if not s.hidden
    ],
    labels=lambda s: s.name,
    on_selected=do_something_with_syntax,
)
```

The API might look something like:

```python
def show_selection_panel(
    window,
    items, # `list` of items of whatever type
    *,
    flags=None,
    labels=str, # Function producing a label from an item
    selected=NOT_GIVEN, # An item, not an index
    on_selected=None, # When an item is chosen.
    on_cancel=None, # When the panel is cancelled.
    on_highlighted=None, # When an item is highlighted. Receives the item.
):
```

Does this seem like a good, generally useful function to provide?

**Comment by keith-hall** [comment]
Sounds useful to me - in some cases it's annoying to have to "store" the list somewhere manually just to know which item was picked, so having `sublime_lib` take care of it would be awesome.

**Comment by FichteFoll** [comment]
(I don't think I've ever seen a single package using `View.show_popup_menu`. :thinking: )
