### ISSUE TITLE
Not put the Makefile on the root of the project

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/sublime_lib#85]
Just some thoughts mine about it.

I would not put the `Makefile` on the root of the project because it is not a place I would look for it if I would like to build the `docs`, because:
1. This is a python project, so most of times does not make sense to have a `Makefile`. Then, while looking for how to build the `docs`, I did even thought about looking for it on the root of the project (https://github.com/SublimeText/sublime_lib/pull/77 Reformat docs). 
1. The only thing the `Makefile` builds is the docs, then, it would be better to put a  `docs` related file into the `docs` directory. On bigger projects, we could have one `Makefile` per "subproject". If that was the case, our main `Makefile` on the root of the project, would recursively call other make files.
1. The `docs` directory is kinda empty (only the `source` directory inside it), while the root of the project has much more other things, including the `Makefile` which is used exclusively for the `docs` directory, so it should be put inside it for "organization", as in, keep related things together.

**Comment by FichteFoll** [comment]
Considering the Makefile does indeed only serve the purpose of building docs currently, I tend to agree with moving it, although I don't really see a problem in the current situation.

I'll leave the decision to @Thom1729.
