### ISSUE TITLE
Some Ghosts on the new TOC

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/sublime_lib#86]
![image](https://user-images.githubusercontent.com/5332158/50055598-1e520980-0138-11e9-8d89-518c10551edc.png)

**Comment by Thom1729** [comment]
That `modules` directory shouldn't exist anymore. Did you `make clean`?

**Comment by evandrocoan** [comment]
I got this directly from the website:
1. https://sublimetext.github.io/sublime_lib/modules/sublime_lib.html#module-sublime_lib

**Comment by Thom1729** [comment]
Was vestigial stuff. New PR should remove it.
