### ISSUE TITLE
Lightweight async mini-framework

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#90]
The builtin options for deferred actions in Sublime plugins are:

- `set_timeout()` (which can block the main thread).
- `set_timeout_async()` (which can block the single, shared async thread).
- DIY manually using threads.

The relative ease and convenience of the former two options leads devs to use them when a more robust solution would be appropriate. `set_timeout_async()`, in particular, seems to be misunderstood — blocking operations (such as IO or sleep) in a `set_timeout_async()` callback will block everyone else's callbacks.

A simple-but-robust mechanism for deferred and async code could be very helpful to package developers and valuable to end users.

### Requirements

Package developers write deferred or async code to:

- Schedule code to run later.
- Keep blocking operations off of shared threads.
- Yield control to other tasks during expensive operations.
- Asynchronously wait for some condition.
- Interact with external processes such as Node.

Depending on the circumstances, the same task might be run with very different execution strategies. For instance, an expensive task like compiling macros might typically run on its own thread, but to calculate test coverage it must run on the main thread. The developer must be able to switch out execution strategies on the fly.

Some of Sublime's API methods (such as `Window.show_quick_panel`) run deferred callbacks. A developer should be able to suspend their code while awaiting a callback and then continue execution in the same manner as before (e.g. on the same thread).

In order to provide an attractive and convenient alternative to blindly calling `set_timeout_async()`, the API must be extremely simple.

### Non-requirements

Python has a global interpreter lock that prevents more than one thread from running Python code simultaneously. The workaround is multiprocessing. A convenient abstraction for this is outside the scope of this proposal.

Managing shared state in async code can be hard. While we shouldn't introduce unnecessary footguns, nor should we try to solve all of the ones that already exist.

Python threads are cooperative; a single thread can hog the CPU. We can't stop this. We can, however, provide abstractions that avoid unexpected conflicts (e.g. blocking IO in the shared async thread).

### Prior art

Python's [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html) module provides `Future` and `Executor` abstractions. These are useful primitives, particularly `Future`. In principle, custom `Executor` classes could encapsulate `set_timeout` and `set_timeout_async`. However, the API is low-level. `Future`s are atomic; there is no abstraction for a task containing several units of work. In addition, there is no notion of scheduling or timing.

Python's newer [asyncio](https://docs.python.org/3/library/asyncio.html) system is more powerful. It includes a native task abstraction and provides scheduling. However, it comes with several drawbacks:

- It's 3.5+, so we'd have to vendor it (and it is not small).
- The “good” syntax with `async`/`await` can't be backported. The alternative (generator functions with `@asyncio.coroutine`) is already deprecated and scheduled for removal.
- It's designed around a single global event loop. Sublime has two event loops out-of-the-box, and package developers may have their own.
- It comes with its own nonblocking IO functions that return `Future` objects. It is not safe to use with blocking IO. This requires more deliberate awareness and care from developers and could maintain the existing footgun of blocking the shared async thread.

JavaScript's [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) represents a `Future`-like atomic task. However, unlike a Python `Future`, a `Promise` is designed to be constructed by a user. This allows it to easily encapsulate callbacks and other ‘out-of-context’ async code.

UnitTesting's [deferred tests](https://github.com/SublimeText/UnitTesting/blob/master/unittesting/core/st3/runner.py) implement a task abstraction using generator functions. It's a lightweight system that — unsurprisingly — maps pretty well onto typical Sublime use cases. It unconditionally uses `set_timeout()`, but the approach is solid.

[resumeback](https://fichtefoll.github.io/resumeback/) uses a generator-based approach to ‘linearize’ callbacks. It's not designed for more general async or deferred code, but the core principle is nearly full continuation passing, and it could be extended.

### Proposed solution

The solution I'm thinking of is based largely on UnitTesting's, but with an additional level of abstraction.

A “task” is a generator function that yields one or more “actions”. An action might be an integer (indicating a delay), `None` (yield to other threads and resume without delay), a function (wait for a condition), or a `Future` object. A task is invoked by a “runner”, which is a function that implements some scheduling strategy.

The API surface would be a few runners and some utility functions. We'd have (at least) a runner for `set_timeout`, one for `set_timeout_async`, one that spawns a brand-new thread, and one that's synchronous and uses `sleep()`. Example:

```python
def async_example():
    print("Hello...")
    yield 1000 # wait 1000 ms
    print("World!")

set_timeout_runner.run(async_example)
set_timeout_async_runner.run(async_example)

thread_runner = ThreadRunner()
thread_runner.run(async_example)
```

We'd also provide a `promise` function to handle functions like `show_quick_panel`:

```python
def callback_example(window, items):
    index = yield promise(lambda resolve, reject:
        window.show_quick_panel(items, resolve)
    )

    if index >= 0:
        print(items[index])
    else:
        print("Nothing selected.")

set_timeout_runner.run(async_example)
```

Of course, since we already have a convenience wrapper for `show_quick_panel`, we could have it return a `Future`:

```python
from sublime_lib import show_selection_panel, Cancelled

def callback_example(window, items):
    try:
        result = yield show_selection_panel()
        print(result)
    except Cancelled:
        print("Nothing selected.")
```

Finally, we could provide simple decorators to turn tasks into regular functions returning `Future`s:

```python
thread_runner = ThreadRunner()

@async_decorator(thread_runner)
def do_expensive_thing(items):
    for item in items:
        expensive_operation(item)
        yield
```

A thread-pool runner with multiple threads might be handy as well, though that's more code.

### Comparison to `resumeback`

`resumeback` example code:

```py
from resumeback import send_self

@send_self
def main():
    this = yield
    arbitrary_value = 10

    number = yield ask_for_user_input("Please enter a number", this.send)
    number = str(number)
    print("Result:", number * arbitrary_value)
```

Example equivalent code:

```py
from sublime_lib import async_decorator, synchronous_runner

@async_decorator(synchronous_runner)
def main():
    arbitrary_value = 10

    number = yield promise(
        lambda resolve, reject: ask_for_user_input("Please enter a number", resolve)
    )
    number = str(number)
    print("Result:", number * arbitrary_value)
```

Or, if `ask_for_user_input` returns a `Future`:

```py
from sublime_lib import async_decorator, synchronous_runner

@async_decorator(synchronous_runner)
def main():
    arbitrary_value = 10

    number = yield ask_for_user_input("Please enter a number")
    number = str(number)
    print("Result:", number * arbitrary_value)
```

The key philosophical difference is that this proposal abstracts out the details of how the continuation is called. That is implemented in the runner, and tasks are runner-agnostic. In `resumeback`, you explicitly choose `send` versus `send_await` and so on.

### Discussion

The proposed solution should hopefully strike a good balance between simplicity, generality, and usability. I'm optimistic that a no-frills implementation (sans docstrings, etc) should be 150 lines or fewer.

Is this a reasonable feature to have in sublime_lib? I think that it is. Asynchronicity is critically important to many plugins, and Sublime's built-in event loops are widely used but often misused. It's very easy for a developer to call `set_timeout_async()` without understanding the ramifications, whereas manual threading can seem like a hassle to the uninitiated. We can provide a “[pit of quality](https://blogs.msdn.microsoft.com/ericlippert/2007/08/14/c-and-the-pit-of-despair/)” where it's easy to do the right thing.

Is this the right implementation? My perspective is JavaScript-heavy, which I'm sure is why I like using `Future` as a central primitive. I've been working on the idea for a few weeks, and I think I've seen and tried out all of the reasonable existing options. I've used UnitTesting's similar task system a lot, and I think it's a good match for most practical use cases.

Thoughts? I can put up a PR in the next couple of days that demonstrates the core functionality.

**Comment by FichteFoll** [comment]
Skipped over a few segments but I can probably only comment properly from Thursday onwards.

**Comment by Thom1729** [comment]
Thanks. No rush; I expect that this will take a good bit of consideration and revision. (I think I fixed the resumeback example.)

**Comment by Thom1729** [comment]
Since Python 3.8 provides `async`, this probably isn't necessary.
