### ISSUE TITLE
Type annotations and MyPy checking

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#91]
http://mypy-lang.org/

- Add type annotations to all exported functions, methods, and values.
- Create stub files for `sublime`/`sublime_plugin`. (The [LSP stubs](https://github.com/tomv564/LSP/tree/master/stubs) are outdated.)
- Set up MyPy to validate type safety.
- Integrate type annotations into documentation.

**Comment by FichteFoll** [comment]
Do you intend to do inline annotations? I found the 3.6 syntax with variable annotations quite favorable over comments (not to mention that `typing` would become yet another dependency otherwise), so I'd be wary of that.

I sure wish we were on 3.7 already :^)

**Comment by Thom1729** [comment]
I figured we'd annotate at least all exports and all public methods of exported classes. We can use syntactic annotations for nearly all of this, but there are probably a couple of exported constants that will require comment annotations.

**Comment by Thom1729** [comment]
Fixed by #116.
